
version: "3.9"

services:

  redis:
    image: redis
    #commend: 
    ports:
      - "6380:6379"
#    develop:
#      watch:
#        - action: sync
#          path: /
#          target: /log
    volumes:
        - redis_data:/data 
        - ./redis_default_data  #Mount to host, to output redis config
    networks:
        - bench_the_query # to be replaced by an API Gateway or VPN-like layer in the future modular tests ###Futrue





volumes:
  redis_data:  # Declare a named volume for Redis to store its data
networks:
    bench_the_query:
        external: false




