version: "3.8"

services:

  redis:
    build: ./redis # Redis Stack image + Lua script for fake dataloading; #load test works with default fake dataset, See readme.
    ports:
      - "6370:6379" # This field is fixed until later dev changes ; container: 6379
    #environment:
      # Preservered field for scirpt control feature; this helps future development in 
      # multilevel query/ subquery
      # CLI in defualt dataset benchmark 

  graphql:
    build: ./generic_graphQL  # Allows user to query with Redis CLI
    ports:
      - "4000:4000" # container: graphQL port 4000 pred-defined in code 
    depends_on: #dependent images will get built first
      - redis
    #environment:
      # Preservered field for scirpt control feature; this helps future development in 
      # multilevel query/ subquery

  fast_api:
    build: ./generic_FastAPI/restAPI/fastAPI  # Allows user to query with Redis CLI
    ports:
      - "8000:8000" # container: fastAPI port 8000 pred-defined in code 
    depends_on: #dependent images will get built first
      - redis
    #environment:
      # Preservered field for scirpt control feature; this helps future development in 
      # multilevel query/ subquery
      # CLI in defualt dataset benchmark 

  
# Next: 


#### aggregated containers: 
# docker-compose  -d -p bench_query up: starts the containers in background, non-blocking 

# docker-compose -p bench_query up: blocking; shows all logs

#####
# docker-compose build  : create image

# docker-compose up  /   docker-compose up  -p bech_q : build automatically; docker check image upate

# docker-compose up --build     : force reebuild and run
