# Docker compose for Redis
# Localhost with blindmount at ./redis_presist 
# 
version: "3.9"

services:

  redis:
    image: redis
    #commend: 
    ports:
      - "6380:6379"
#    develop:
#      watch:
#        - action: sync
#          path: /
#          target: /log
    volumes: # tip: docker volume prune -f to clear docker cached volumes
      #initial setip (for later: wired by script)
      #redis-cli -h localhost -p 6379 < ./import_users.redis   
      #redis-cli -h localhost -p 6380 CONFIG GET * > redis_runtime.conf
      - ./redis_presist:/opt/app/static 

      - redis_data:/data  # Other Redis/ non-user defined data 
      # Alternative syntax ref
      #- type: bind # To place redis config, Redis AOF or shared localhost files. 
      #  source: ./redis_presist # dataset  source: https://github.com/redis-developer/redis-datasets/blob/master/user-database/README.md
      #  target: /opt/app/static

      # for later: add flush cache.sh

    networks:
        - bench_the_query # to be replaced by an API Gateway or VPN-like layer in the future modular tests ###Futrue





volumes:
  redis_data:  # container & non-user setting data
networks:
    bench_the_query:
        external: false




