version: "3.8"

networks:
  bench_q_debug:
    external: true  # This refers to the network from the first Compose file; GPT assisted

services:
  k6:
    image: grafana/k6

    ports:
      - "1100:1100"
    volumes:
      - ./results:/results
      - ./scripts:/scripts
    networks:
      - bench_q_debug  # Attach to the shared network
    environment:
      - FastAPI_URL= http://fast_api:8000/ 
      - K6_OUT=influxdb=http://influxdb:8086/k6db
      
    #  - GRAPHQL_URL=http://graphql:4000/  # Set the environment variable to the GraphQL service URL 
    # depends_on:
    #   - graphql  # Ensure the 'graphql' service is ready before running tests
   
    command: run  /scripts/fastAPI_test.js 
