version: '3.8'
# Allow users to build graphql-redis-proxy images locally 
services:
  graphql-redis-proxy:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6370

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
