services:
  riot:
    image: riotx/riot:v4.1.3
    container_name: riot-container
    volumes:
      - ./app/data/df_final_features.json:/data:ro # bind mount json from local host
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: import /data/df_final_features.json --redis-host redis --redis-port 6379
  
    networks:
      - bench_the_query # to be replaced by an API Gateway or VPN-like layer in the future modular tests ###Futrue

networks:
    bench_the_query:
        external: false


