version: "3.8"


networks: 
  bench_q_debug:
    external: true 
services:

  fast_api:
    build: ./ # Allows user to query with Redis CLI
    ports:
      - "8000:8000" # container: fastAPI port 8000 pred-defined in code 
    depends_on: #dependent images will get built first
      - redis
    networks:
      - bench_q_debug 