version: "3.8"


networks: 
  bench_q_debug:
    external: true 
services:

  redis:
    container_name: redis_bench_query_debug
    build: ./ # Redis Stack image + Lua script for fake dataloading; #load test works with default fake dataset, See readme.
    ports:
      - "6370:6379" # This field is fixed until later dev changes ; container: 6379
    #environment:
      # Preservered field for scirpt control feature; this helps future development in 
      # multilevel query/ subquery
      # CLI in defualt dataset benchmark 
    networks:
      - bench_q_debug